\cleardoublepage 

# (APPENDIX) Apéndice {-}

# Formato de los datos de la aplicación

En esta sección se describirá el formato que deben poseer los datos que necesitará la aplicación.

## Score y Rating

Este módulo esta compuesto de 4 pestañas:

### Scoring


Este archivo debe tener la extensión *.txt* ó *csv*. Todos sus campos deben ser numéricos, en caso de haber categorías deben estar expresadas en números. Esta data es escencial para la contrucción del modelo de Scoring. 

- Una de sus columnas deben tener el nombre "Creditability"
    + Para clientes en Default 1
    + Para clientes en regla 0

### Proyección Scoring

En esta sección se realizan predicciones a partir del modelo Score calculado. Los campos de los datos deben ser exatamente igual a los de los datos de entrenamiento, con la excepción de que el campo "Creditability" no debería existir.

### Rating

Archivo con extensión *.csv* ó *.txt* el cual debe estar conformado por dos campos:

- pd: Campo numerico indicando probabilidad de incumplimiento
- r: Campo categórico que indica rating del cliente

### Proyección Rating

Archivo con extensión *.csv* ó *.txt* el cual debe tener una única entrada numérica entre 0 y 1 correspondiente a la probabilidasd de incumplimiento.


## Pérdida por incumplimiento


### Pérdida por cliente

Archivo con extensión *.csv* ó *.txt* el cual debe tener una única data númerica entre 0 y 1 correspondiente al porcentaje de pérdida luego del Default.

### Pérdida por cliente

Archivo con extensión *.csv* ó *.txt* el cual debe tener dos campos

+ clases: Variable categórica correspondiente a las clases crediticias

+ perdida: variable numérica entre 0 y 100 correspondiente a la perdida por clase


## Matriz de transición

### Migraciones históricas

Archivo con extensión *.csv* ó *.txt* el cual debe tener dos campos

+ inicio: Variable categórica correspondiente a la clase inicial del cliente

+ fin:  Variable categórica correspondiente a la clase final del cliente

## CreditRisk+

### Exposición

Archivo con extensión *.csv* ó *.txt* el cual debe tener una única data númerica correspondiente al valor deudor del credito.

### Probabilidad de incumplimiento

Archivo con extensión *.csv* ó *.txt* el cual debe tener una única data númerica correspondiente a la probabilidad de incumplimiento de cada cliente.


### Pérdidas dado el incumplimiento

Archivo con extensión *.csv* ó *.txt* el cual debe tener una única data númerica correspondiente a la pérdida esperada por cliente en pocentaje de 0 a 1.

## CreditMetrics

### Exposición

Archivo con extensión *.csv* ó *.txt* el cual debe tener dos campos:

+ creditos: Variable numérica correspondiente al monto del crédito restante a pagar por el cliente.

+ calif: Variable categórica correspondiente a la clasificación crediticia del cliente.

### Martriz de transición

Archivo con extensión *.csv* ó *.txt* el cual debe  poseer :

+  Un campo con nombre *inicio/fin* con las categorias crediticias

+ Una matriz numérica correspondiente a las probabilidades de transición entre clases, la suma de cada columna debe ser 1.


### Pérdida por clase




Archivo con extensión *.csv* ó *.txt* el cual debe  poseer los siguientes campos:


+ Clase: Variable categórica con las distintas clases crediticias.

+ Pérdida esperada: variable numérica entre 0 y 100 correspondiente a la pérdida esperada por cliente

+ Mínimo esperado: variable numérica entre 0 y 100 correspondiente a la mínima pérdida esperada por cliente

+ Máximo esperado: variable numérica entre 0 y 100 correspondiente a la máxima pérdida esperada por cliente


## BackTesting

Archivo con extensión *.csv* ó *.txt* el cual debe  poseer los siguientes campos:

- Fecha en formato dia/mes/año (27/03/2018)
- Valor numérico que contenga la información del VaR de ese día
- Valor numérico que contenga el valor nominal del portafolio

Es importante mencionar que el archivo debe contener 252 observaciones

## Indicadores Contables


Archivo con extensión *.csv* ó *.txt* el cual debe  poseer los siguientes 2 campos:












